import { useEffect, useRef, useState, lazy, Suspense, type FormEvent, type ReactNode } from 'react';
import { motion, useReducedMotion, useMotionValue, useSpring } from 'motion/react';
import { ArrowUpRight, ArrowRight, ArrowDown, Check, ChevronDown, Menu, Play, Pause, MapPin, Plus, Heart, Sparkles, CheckCircle2, RotateCcw } from 'lucide-react';
import { Button } from './components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from './components/ui/dialog';
import { Marquee } from './components/magicui/marquee';
import { type Group } from './data';
import { useSite } from './site-context';
const Admin = lazy(() => import('./Admin'));
import { filterGroups, validateEnquiry } from './lib/matching.mjs';

type Modal = { type: 'booking'; group?: Group; age?: string; context?: string } | { type: 'quiz' } | { type: 'feedback' } | { type: 'video'; id: string; title: string } | null;
type Booking = (group?: Group, age?: string, context?: string) => void;
const photo = (name: string, small = false) => `/media/${name}${small ? '-small' : ''}.webp`;
function Reveal({ children, className = '' }: { children: ReactNode; className?: string }) {
  const reduce = useReducedMotion();
  return <motion.div className={className} initial={reduce ? false : { opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: .55, ease: [.22, 1, .36, 1] }} viewport={{ once: true, amount: .08 }}>{children}</motion.div>;
}
function Eyebrow({ children, light = false }: { children: ReactNode; light?: boolean }) { return <div className={`eyebrow ${light ? 'light' : ''}`}><span />{children}</div>; }
function Photo({ name, alt, className = '', eager = false }: { name: string; alt: string; className?: string; eager?: boolean }) {
  const { media } = useSite();
  return <img src={media?.[name] || photo(name)} srcSet={media?.[name] || name === 'review' ? undefined : `${photo(name, true)} 640w, ${photo(name)} 1680w`} sizes="(max-width: 640px) 100vw, 50vw" className={className} alt={alt} loading={eager ? 'eager' : 'lazy'} decoding="async" />;
}
function Header({ book, adult = false }: { book: Booking; adult?: boolean }) {
  const [menu, setMenu] = useState(false);
  const trigger = useRef<HTMLButtonElement>(null); const pendingAnchor = useRef<string | null>(null);
  const links = [['Направления', '/#styles'], ['Расписание', '/#schedule'], ['Цены', '/#prices'], ['О школе', '/#about'], ['Контакты', '/#contacts']];
  return <header className="header"><div className="header-inner"><a href="/" className="brand" aria-label="YOUKEY — главная"><img src={photo('logo')} alt="YOUKEY" width="112" height="60" /><span>ШКОЛА<br />ТАНЦЕВ</span></a><nav className="desktop-nav" aria-label="Основное меню">{links.map(([name, href]) => <a key={name} href={href}>{name}</a>)}</nav><div className="header-actions"><a className="adult-link" href="/adults">18+ <ArrowUpRight size={14} /></a><Button size="small" onClick={() => book()}>{adult ? 'Выбрать занятие' : 'Бесплатное занятие'} <ArrowUpRight size={16} /></Button><button ref={trigger} className="icon-button menu-toggle" onClick={() => setMenu(true)} aria-label="Открыть меню"><Menu /></button></div></div><Dialog open={menu} onOpenChange={setMenu}><DialogContent className="menu-dialog" onCloseAutoFocus={e => { e.preventDefault(); trigger.current?.focus({ preventScroll: true }); const target = pendingAnchor.current; if (target) { pendingAnchor.current = null; requestAnimationFrame(() => { document.getElementById(target)?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' }); }); } }}><DialogTitle>YOUKEY</DialogTitle><DialogDescription>Найди свой ритм</DialogDescription><nav aria-label="Мобильное меню">{[...links, ['Преподаватели', '/#teachers'], ['Родителям', '/parents'], ['Танцы 18+', '/adults']].map(([name, href]) => <a href={href} key={name} onClick={e => { if (href.startsWith('/#') && window.location.pathname === '/') { e.preventDefault(); pendingAnchor.current = href.slice(2); window.history.pushState(null, '', href); } setMenu(false); }}>{name}<ArrowUpRight /></a>)}</nav><Button onClick={() => { setMenu(false); book(); }}>{adult ? 'Оставить заявку' : 'Записаться бесплатно'} <ArrowRight /></Button></DialogContent></Dialog></header>;
}
function Hero({ book, quiz, video }: { book: Booking; quiz: () => void; video: () => void }) {
  const { settings, media } = useSite();
  const reduce = useReducedMotion();
  const x = useMotionValue(0); const y = useMotionValue(0);
  const springX = useSpring(x, { stiffness: 110, damping: 20 }); const springY = useSpring(y, { stiffness: 110, damping: 20 });
  const [color, setColor] = useState(false);
  return <section className="hero" onPointerMove={e => { if (!reduce && e.pointerType === 'mouse') { const r = e.currentTarget.getBoundingClientRect(); x.set((e.clientX - r.left - r.width / 2) * .022); y.set((e.clientY - r.top - r.height / 2) * .022); } }} onPointerLeave={() => { x.set(0); y.set(0); }}>
    <div className="hero-lines" aria-hidden="true" /><div className="hero-inner"><div className="hero-copy"><Eyebrow light>{settings.address.toUpperCase()}</Eyebrow><motion.h1 initial={reduce ? false : { y: 28, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: .8 }}>СВОЙ СТИЛЬ.<br /><span>СВОИ ЛЮДИ.</span></motion.h1><div className="hero-description"><span className="little-star" aria-hidden="true">✳</span><p>Современные танцы для детей <strong>4–17 лет.</strong><br />Место, где можно быть собой.<br />Даже если пока не умеешь танцевать.</p></div><div className="hero-buttons"><Button onClick={() => book()}>Попробовать бесплатно <ArrowUpRight size={20} /></Button><button className="text-link light-link" onClick={quiz}>Подобрать группу <ArrowRight size={18} /></button></div><div className="hero-bottom"><div className="tiny-avatars"><img src={photo('team', true)} alt="" /><img src={photo('kids', true)} alt="" /><img src={photo('dance', true)} alt="" /></div><span>Начни с первого движения.<br /><b>Остальное — вместе.</b></span></div></div>
    <div className={`hero-visual ${color ? 'in-color' : ''}`}><div className="photo-index">YOUKEY COMMUNITY / 01</div><img src={media?.team || photo('team')} alt="Команда школы YOUKEY вместе с руководителем Александрой Шеберстовой" fetchPriority="high" width="925" height="1103" /><div className="hero-photo-bottom"><button className="video-button" onClick={video}><span><Play size={16} fill="currentColor" /></span>Заглянуть в YOUKEY<ArrowUpRight size={16} /></button></div><motion.button style={reduce ? undefined : { x: springX, y: springY }} className="hero-sticker" onClick={() => setColor(!color)} aria-pressed={color} aria-label="Добавить цвет командной фотографии"><span>МЕНЬШЕ СТЕСНЕНИЯ</span><b>БОЛЬШЕ<br />ТЕБЯ!</b><Sparkles size={23} /></motion.button></div></div><a href="#find" className="hero-scroll" aria-label="Перейти к выбору возраста"><ArrowDown size={18} /></a>
  </section>;
}
function RhythmStrip() {
  const [paused, setPaused] = useState(false);
  return <div className="rhythm-strip"><Marquee paused={paused}><span>ТАНЦУЙ ПО-СВОЕМУ</span><span className="strip-star">✳</span><span>НАЙДИ СВОИХ</span><span className="strip-star">✳</span><span>YOUKEY</span><span className="strip-star">✳</span></Marquee><button className="strip-pause" onClick={() => setPaused(!paused)} aria-label={paused ? 'Продолжить анимацию ленты' : 'Приостановить анимацию ленты'}>{paused ? <Play size={14} /> : <Pause size={14} />}</button></div>;
}
function AgeSection() { const { ages } = useSite(); return <section id="find" className="section age-section"><Reveal><div className="section-heading"><div><Eyebrow>01 / ТВОЙ ПЕРВЫЙ ШАГ</Eyebrow><h2>Каждому возрасту —<br /><span className="muted">свой ритм.</span></h2></div><p>От первых движений до собственной хореографии.<br />Начнём с того, сколько лет вашему ребёнку.</p></div></Reveal><div className="age-grid">{ages.map((age, i) => <Reveal key={age.slug} className="age-reveal"><a className={`age-card age-${i}`} href={`/ages/${age.slug}`}><div className="age-photo"><Photo name={age.image} alt="Ученики школы танцев YOUKEY" /><span className="age-number">{age.label}<small>ЛЕТ</small></span><span className="circle-arrow"><ArrowUpRight /></span></div><div className="age-card-copy"><span className="micro">{['ЗНАКОМИМСЯ С ТАНЦЕМ', 'ПРОБУЕМ И ОТКРЫВАЕМ', 'ИЩЕМ СЕБЯ', 'ПРОЯВЛЯЕМ СЕБЯ'][i]}</span><h3>{age.title}</h3><p>{age.text}</p></div></a></Reveal>)}</div><div className="age-foot"><span><Check size={16} /> Можно без опыта</span><span><Check size={16} /> Группы по возрасту</span><span><Check size={16} /> Выступления по желанию</span><a href="/adults">А если мне уже 18? <ArrowUpRight size={16} /></a></div></section>; }
function About({ quiz, video }: { quiz: () => void; video: () => void }) { return <section id="about" className="section about-section"><Reveal className="about-photo"><Photo name="dance" alt="Танцевальная постановка учеников школы" /><button className="round-play" onClick={video} aria-label="Посмотреть видео о тренировках"><Play fill="currentColor" size={25} /></button><span className="photo-caption">ТАНЦЫ НАЧИНАЮТСЯ С ЛЮДЕЙ</span><span className="photo-note">Живые кадры из истории школы</span></Reveal><Reveal className="about-copy"><Eyebrow>02 / МЕСТО ДЛЯ СВОИХ</Eyebrow><h2>Здесь можно<br />начинать<br /><span className="pink-text">по-разному.</span></h2><p className="intro-copy">Не нужно сразу попадать в ритм.<br />Для начала — просто прийти.</p><div className="reassurance"><div><span>01</span><div><h3>«Он никогда не танцевал»</h3><p>И это нормально. Начнём с первых движений и подберём подходящую группу.</p></div></div><div><span>02</span><div><h3>«Она немного стесняется»</h3><p>Дадим время освоиться, познакомиться с педагогом и почувствовать себя своей.</p></div></div><div><span>03</span><div><h3>«А если не хочется на сцену?»</h3><p>Можно танцевать для себя. Выступления и съёмки — только по желанию.</p></div></div></div><button className="text-link" onClick={quiz}>Найдём вашу группу <ArrowUpRight size={20} /></button></Reveal></section>; }
function StylesSection() { const { styles } = useSite(); return <section id="styles" className="section styles-section"><Reveal><div className="section-heading"><div><Eyebrow>03 / НАПРАВЛЕНИЯ</Eyebrow><h2>Что тебя <span className="serif-word">двигает?</span></h2></div><p>Необязательно знать названия стилей.<br />Начни с того, что тебе нравится.</p></div></Reveal><div className="style-list">{styles.slice(0, 6).map((s, i) => <Reveal key={s.slug}><a className="style-row" href={`/styles/${s.slug}`}><span className="style-number">0{i + 1}</span><h3>{s.name}</h3><span className="style-feeling">{s.feeling}</span><img src={photo(s.image, true)} alt="" loading="lazy" /><span className="style-arrow"><ArrowUpRight /></span></a></Reveal>)}</div><a href="/styles/kids-dance" className="text-link more-style">Ещё для самых юных — Kids Dance <ArrowUpRight size={17} /></a></section>; }
function Trial({ book }: { book: Booking }) { return <section className="trial-section"><div className="section"><Reveal><div className="section-heading"><div><Eyebrow light>04 / ДАВАЙ ЗНАКОМИТЬСЯ</Eyebrow><h2>Первый раз?<br /><span>Это бесплатно.</span></h2></div><div className="trial-price">0<span>₽</span><small>ПЕРВОЕ ЗАНЯТИЕ</small></div></div></Reveal><div className="trial-steps">{[['Знакомимся', 'Расскажите про возраст, опыт и то, что нравится ребёнку.'], ['Пробуем танцевать', 'Настоящее занятие, первая связка, знакомство с группой.'], ['Находим своё', 'Педагог даст обратную связь и поможет выбрать направление.']].map(([title, text], i) => <Reveal key={title}><span className="step-number">0{i + 1}</span><h3>{title}</h3><p>{text}</p></Reveal>)}</div><div className="trial-bottom"><p><Heart size={20} /> Продолжать или нет — решаете вы. Никаких обязательств.</p><Button onClick={() => book()}>Хочу попробовать <ArrowUpRight /></Button></div></div></section>; }
function Schedule({ book, initialAge = '', initialStyle = 'all', adult = false }: { book: Booking; initialAge?: string; initialStyle?: string; adult?: boolean }) {
  const { groups, ages } = useSite(); const [age, setAge] = useState(initialAge); const [day, setDay] = useState('all'); const [style, setStyle] = useState(initialStyle); const [expanded, setExpanded] = useState(false);
  const matches: Group[] = filterGroups(groups, { age, day, style, adult });
  const shown = expanded ? matches : matches.slice(0, 6);
  const changed = age !== '' || day !== 'all' || style !== 'all';
  return <section id="schedule" className="section schedule-section"><Reveal><div className="section-heading"><div><Eyebrow>05 / ВСТРЕТИМСЯ В ЗАЛЕ</Eyebrow><h2>Танцы в твоём<br /><span className="muted">расписании.</span></h2></div><p>Выбирай удобные дни и время.<br />Группу и возможность записи подтвердит администратор.</p></div></Reveal><div className="schedule-filters">{!adult && <label>Возраст<select aria-label="Возраст для расписания" value={age} onChange={e => { setAge(e.target.value); setExpanded(false); }}><option value="">Все возрасты</option>{ages.map(a => <option value={a.slug} key={a.slug}>{a.label} лет</option>)}</select><ChevronDown size={16} /></label>}<label>Когда удобно<select aria-label="Дни занятий" value={day} onChange={e => { setDay(e.target.value); setExpanded(false); }}><option value="all">Любой день</option><option value="weekdays">Будни</option><option value="weekend">Выходные</option><option value="early">Будни до 17:00</option><option value="late">Будни с 17:00</option></select><ChevronDown size={16} /></label><label>Направление<select aria-label="Направление" value={style} onChange={e => { setStyle(e.target.value); setExpanded(false); }}><option value="all">Все направления</option>{[...new Set(groups.filter(g => Boolean(g.adult) === adult).map(g => g.style))].map(s => <option key={s}>{s}</option>)}</select><ChevronDown size={16} /></label>{changed && <button className="filter-reset" onClick={() => { setAge(''); setDay('all'); setStyle('all'); setExpanded(false); }}><RotateCcw size={16} /> Сбросить</button>}</div><p className="results-label" role="status">{matches.length ? `Групп по выбранным параметрам: ${matches.length}` : 'Нет групп с такими параметрами'}</p><div className="group-grid">{shown.map(g => <GroupCard key={g.id} group={g} book={book} />)}</div>{matches.length === 0 && <div className="empty-state"><h3>Найдём другое время?</h3><p>Измените фильтры или оставьте запрос на подбор. Группы с неуточнённым возрастом не попадают в возрастную выборку.</p><Button variant="dark" onClick={() => book(undefined, undefined, `Подбор: возраст ${age}, время ${day}, направление ${style}`)}>Помогите подобрать <ArrowRight /></Button></div>}{matches.length > 6 && <button className="load-more" onClick={() => setExpanded(!expanded)}>{expanded ? 'Свернуть расписание' : `Показать все группы (${matches.length})`}<ChevronDown className={expanded ? 'rotated' : ''} size={18} /></button>}<p className="schedule-note">Преподаватели, уровень, длительность и свободные места уточняются перед записью. Возраст «6+» означает нижнюю границу, состав группы подтвердит администратор.</p></section>;
}
function GroupCard({ group: g, book }: { group: Group; book: Booking }) { return <article className="group-card"><div className="group-top"><span className="group-days">{g.days}</span><span className="group-age">{g.age}</span></div><div className="group-time">{g.time}<ArrowUpRight size={24} /></div><h3>{g.style}</h3><p>{g.teacher ? `Педагог: ${g.teacher}` : 'Преподаватель уточняется'}<br />{g.level || 'Уровень уточняется'}{g.duration ? ` · ${g.duration} мин` : ''}<br />{g.capacity != null && g.enrolled != null ? `Свободных мест: ${Math.max(0, g.capacity - g.enrolled)}` : 'Наличие мест уточняется'}</p><button disabled={g.capacity != null && g.enrolled != null && g.enrolled >= g.capacity} onClick={() => book(g)}>{g.adult ? 'Уточнить и записаться' : 'Попробовать бесплатно'}<ArrowRight size={18} /></button></article>; }
function Teachers({ video }: { video: () => void }) { return <section id="teachers" className="section teachers-section"><Reveal className="teacher-photo"><Photo name="founder" alt="Александра Шеберстова — руководитель школы YOUKEY" /><div className="teacher-photo-label"><span>АЛЕКСАНДРА ШЕБЕРСТОВА</span><small>Руководитель YOUKEY</small></div></Reveal><Reveal className="teacher-copy"><Eyebrow>06 / ЛЮДИ YOUKEY</Eyebrow><h2>Рядом — тот,<br />кто <span className="pink-text">понимает.</span></h2><blockquote>«Детям очень нужно место, где они смогут проявить себя, довериться окружающим, отдохнуть душой».</blockquote><p>Александра Шеберстова<br /><span className="muted">Основатель и руководитель школы</span></p><button className="text-link" onClick={video}>Как проходят тренировки <Play size={17} /></button><div className="teacher-note">Состав преподавателей и их группы обновляются. При записи мы уточним, кто ведёт выбранное занятие.</div></Reveal></section>; }
function Community({ video }: { video: () => void }) { const { events = [] } = useSite(); return <section className="community-section" id="projects"><div className="section"><Reveal><div className="section-heading"><div><Eyebrow light>07 / БОЛЬШЕ, ЧЕМ ДВИЖЕНИЯ</Eyebrow><h2>Из зала —<br /><span className="pink-text">в твою историю.</span></h2></div><p>Первая связка. Своё окружение.<br />Съёмки, проекты и настоящая сцена —<br />когда тебе этого захочется.</p></div></Reveal><div className="community-grid"><Reveal className="community-main"><Photo name="stage" alt="Ученики школы выступают на сцене" /><button onClick={video}><Play size={17} fill="currentColor" /> Смотреть выступление <ArrowUpRight size={18} /></button></Reveal><Reveal className="community-side"><Photo name="kids" alt="Детская постановка из архива школы" /><div><span className="micro">ТВОЙ ТЕМП. ТВОЙ ВЫБОР.</span><h3>На сцену —<br />по желанию.</h3><p>Танцевать для удовольствия —<br />тоже большая история.</p></div></Reveal></div><div className="event-grid">{events.filter(e => e.active).map(e => <article key={e.id}><span className="micro">{e.date}</span><h3>{e.title}</h3><p>{e.text}</p></article>)}</div><p className="archive-note">Фотографии из истории школы. Актуальные события появятся здесь после объявления.</p></div></section>; }
function Reviews({ video }: { video: () => void }) { return <section className="section reviews-section" id="reviews"><Reveal className="reviews-copy"><Eyebrow>СЛОВО РОДИТЕЛЯМ</Eyebrow><h2>У каждой семьи —<br /><span className="muted">своя история.</span></h2><p>Как родители видят танцевальную жизнь своих детей? Посмотрите видеоотзыв из архива школы.</p><button className="text-link" onClick={video}>Послушать родителей <ArrowUpRight size={18} /></button><a className="review-source" href="https://topstar-dance.ru/#rec417941873" target="_blank" rel="noreferrer">Источник: отзывы на сайте школы ↗</a></Reveal><Reveal className="review-video"><Photo name="review" alt="Кадр видеоотзыва родителя из архива школы" /><button className="round-play" onClick={video} aria-label="Воспроизвести видеоотзыв родителя"><Play fill="currentColor" size={24} /></button><span>ВИДЕООТЗЫВ / АРХИВ ШКОЛЫ</span></Reveal></section>; }
function Prices({ book }: { book: Booking }) { const [promoChoice, setPromo] = useState(true); const { tariffs, settings } = useSite(); const promo = promoChoice && settings.showPromo; return <section id="prices" className="section price-section"><Reveal><div className="section-heading"><div><Eyebrow>08 / ВСЁ ПОНЯТНО</Eyebrow><h2>Твой ритм.<br /><span className="muted">Твой абонемент.</span></h2></div><div className="price-controls"><p>Первое занятие — бесплатно.<br />А дальше выбираете вы.</p>{settings.showPromo && <label className="price-switch"><input type="checkbox" checked={promo} onChange={e => setPromo(e.target.checked)} /><span className="switch-track" /><span>Со скидкой нового ученика</span></label>}</div></div></Reveal><div className="price-grid">{tariffs.map(t => <Reveal key={t.n}><article className={`price-card ${t.n === 8 ? 'featured' : ''}`}><div className="price-card-top"><span>{t.text}</span>{t.n === 8 && <span className="recommended">НАШ ВЫБОР</span>}</div><h3>{t.n}<span>{t.n === 4 ? 'занятия' : 'занятий'}</span></h3><p className="tariff-frequency">{t.n === 8 ? 'Примерно два раза в неделю' : 'Абонемент на месяц'}</p><div className="price-value">{(promo && settings.showPromo ? t.discounted : t.price).toLocaleString('ru-RU')} <span>₽</span>{promo && <del>{t.price.toLocaleString('ru-RU')} ₽</del>}</div><p className="price-period">{promo ? 'в месяц · первые 2 месяца' : 'в месяц · обычная стоимость'}</p><Button variant={t.n === 8 ? 'primary' : 'outline'} onClick={() => book(undefined, undefined, `Интересует абонемент на ${t.n} занятий`)}>Начать с бесплатного <ArrowUpRight size={18} /></Button></article></Reveal>)}</div><div className="price-details">{settings.showPromo && <p><span className="pink-text">АКЦИЯ</span> При покупке абонемента в день пробного занятия — скидка на первые два месяца.</p>}<p><Heart size={25} /><span><b>Многодетным семьям — скидка {settings.multiChildDiscount}%.</b><br />Условия совмещения скидок уточните у администратора.</span></p></div><p className="fine-print">Дополнительные расходы на концерты, костюмы и проекты, а также правила пропусков и возврата уточняются до покупки.</p></section>; }
function FAQ() { const { faq, settings } = useSite(); const telegramUrl = settings.telegram; return <section id="parents" className="section faq-section"><Reveal><Eyebrow>09 / РОДИТЕЛЯМ</Eyebrow><h2>Всё начинается<br /><span className="muted">с вопросов.</span></h2><p>А мы поможем разобраться.</p><a className="text-link" href={telegramUrl} target="_blank" rel="noreferrer">Задать свой в Telegram <ArrowUpRight size={18} /></a></Reveal><div className="faq-list">{faq.map(([q, a]) => <details key={q}><summary>{q}<Plus size={20} /></summary><p>{a}</p></details>)}</div></section>; }
function Contacts({ book, adult = false }: { book: Booking; adult?: boolean }) { const { settings } = useSite(); const telegramUrl = settings.telegram; const vkUrl = settings.vk; const mapUrl = 'https://yandex.ru/maps/?text=' + encodeURIComponent(settings.address); return <section id="contacts" className="contact-section"><div className="section contact-grid"><Reveal><Eyebrow>10 / МЕСТО ВСТРЕЧИ</Eyebrow><h2>Увидимся<br /><span className="pink-text">в YOUKEY.</span></h2><p className="contact-address">{settings.address}</p><p className="muted">Отрадное / Владыкино</p><div className="contact-links"><a href={mapUrl} target="_blank" rel="noreferrer">Построить маршрут <ArrowUpRight /></a><a href={telegramUrl} target="_blank" rel="noreferrer">Написать в Telegram <ArrowUpRight /></a><a href={vkUrl} target="_blank" rel="noreferrer">Мы ВКонтакте <ArrowUpRight /></a></div><button className="text-link" onClick={() => window.dispatchEvent(new Event('youkey-feedback'))}>Задать вопрос через сайт <ArrowUpRight size={17} /></button><p className="contact-note">Перед первым визитом уточните вход и путь до зала у администратора. Фото входа и видео маршрута готовятся.</p></Reveal><Reveal className="map-art"><div className="map-line line-1" /><div className="map-line line-2" /><div className="map-line line-3" /><div className="map-line line-4" /><div className="map-park park-1" /><div className="map-park park-2" /><span className="map-street">АЛТУФЬЕВСКОЕ ШОССЕ</span><div className="map-pin"><MapPin size={32} fill="currentColor" /><span>YOUKEY<b>{settings.address}</b></span></div><span className="map-label">СХЕМА · НЕ В МАСШТАБЕ</span><a href={mapUrl} target="_blank" rel="noreferrer" className="map-open">Открыть в Яндекс Картах <ArrowUpRight size={18} /></a></Reveal></div><div className="section final-cta"><Reveal><span className="micro">ПРОСТО ПРИХОДИ ПОПРОБОВАТЬ</span><h2>Твоё первое<br />движение — <span className="serif-word">здесь.</span></h2><Button onClick={() => book()}>{adult ? 'Уточнить условия и записаться' : 'Записаться бесплатно'} <ArrowUpRight size={22} /></Button><p>Не нужно выбирать школу навсегда.</p></Reveal><span className="giant-asterisk" aria-hidden="true">✳</span></div></section>; }
function Footer() { return <footer className="footer"><div className="footer-top"><a href="/" className="footer-wordmark">YOUKEY</a><p>СВОЙ СТИЛЬ.<br />СВОИ ЛЮДИ.</p><a href="#top" className="back-top" aria-label="Вернуться наверх"><ArrowUpRight size={25} /></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} YOUKEY</span><span>Танцы для детей и подростков · Москва</span><a href="/privacy">Конфиденциальность</a><a href="/parents">Родителям</a></div></footer>; }

function BookingForm({ modal }: { modal: Extract<Modal, { type: 'booking' }> }) {
  const { settings, delivery } = useSite(); const telegramUrl = settings.telegram; const mapUrl = 'https://yandex.ru/maps/?text=' + encodeURIComponent(settings.address);
  const [sent, setSent] = useState(false); const [sending, setSending] = useState(false); const [error, setError] = useState('');
  const [ageValue, setAgeValue] = useState(modal.age || '');
  const group = modal.group; const isAdult = Boolean(group?.adult) || Number(modal.age) >= 18;
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); setError(''); const data = new FormData(e.currentTarget);
    const body = { name: String(data.get('name') || ''), phone: String(data.get('phone') || ''), age: String(data.get('age') || ''), group: group ? `${group.style} · ${group.days} · ${group.time}` : 'Помогите подобрать группу', consent: data.get('consent') === 'on', groupId: group?.id, kind: 'booking', website: String(data.get('website') || ''), context: modal.context || '' };
    const issue = validateEnquiry(body); if (issue) { setError(issue); return; }
    if (group && (Number(body.age) < (group.min ?? 4) || Number(body.age) > (group.max ?? (group.adult ? 100 : 17)))) { setError(`Возраст не соответствует выбранной группе (${group.age}). Выберите другую группу или запросите подбор.`); return; }
    setSending(true);
    try { const response = await fetch('/api/enquiries', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Requested-With': 'YOUKEY' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Не удалось отправить заявку.'); setSent(true); } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка соединения. Попробуйте ещё раз.'); } finally { setSending(false); }
  }
  if (sent) return <div className="success-screen" role="status"><CheckCircle2 size={54} /><DialogTitle>Первый шаг сделан.</DialogTitle><DialogDescription>Заявка сохранена в системе YOUKEY. Группу и время ещё нужно подтвердить с администратором.</DialogDescription><div className="success-details"><b>{group ? `${group.style} · ${group.days} · ${group.time}` : 'Подбор подходящей группы'}</b><p>{settings.address}</p><p>Возьмите удобную одежду, кроссовки и воду. Перед визитом подтвердите группу и время со школой.</p></div><Button asChild><a href={telegramUrl} target="_blank" rel="noreferrer">Связаться со школой <ArrowUpRight /></a></Button><a href={mapUrl} target="_blank" rel="noreferrer" className="text-link">Посмотреть адрес на карте <MapPin size={17} /></a></div>;
  return <><Eyebrow>ДАВАЙ ЗНАКОМИТЬСЯ</Eyebrow><DialogTitle>{isAdult ? 'Время для себя.' : 'Начнём с танца.'}</DialogTitle><DialogDescription>{isAdult ? 'Оставьте запрос — условия взрослой группы нужно подтвердить.' : 'Первое занятие бесплатно. Подберём группу по возрасту и вашим интересам.'}</DialogDescription>{group && <div className="booking-group"><b>{group.style}</b><span>{group.days} · {group.time} · {group.age}</span></div>}<form className="booking-form" onSubmit={submit}><label className="honeypot" aria-hidden="true">Не заполнять<input name="website" tabIndex={-1} autoComplete="off" /></label><label>Как к вам обращаться<input name="name" autoComplete="name" placeholder="Ваше имя" minLength={2} maxLength={80} required /></label><div className="form-row"><label>Телефон<input name="phone" type="tel" autoComplete="tel" placeholder="+7 (999) 123-45-67" maxLength={22} required /></label><label>{isAdult ? 'Ваш возраст' : 'Возраст ребёнка'}<input name="age" type="number" inputMode="numeric" placeholder="Лет" min={isAdult ? 18 : 4} max={isAdult ? 100 : 17} value={ageValue} onChange={e => setAgeValue(e.target.value)} required /></label></div><label className="consent-label"><input type="checkbox" name="consent" required /><span>Согласен на обработку данных по <a href="/privacy" target="_blank" rel="noreferrer">условиям конфиденциальности</a>.</span></label><div className="form-error" role="alert">{error}</div><Button type="submit" disabled={sending}>{sending ? 'Сохраняем…' : isAdult ? 'Оставить заявку' : 'Записаться бесплатно'}<ArrowUpRight size={20} /></Button><p className="form-disclosure">{delivery?.emailConfigured ? 'Заявка сохранится в системе; уведомление будет отправлено школе.' : 'Заявка сохранится в админке. Почтовые уведомления пока не подключены.'}</p></form></>;
}
function Quiz({ book }: { book: Booking }) {
  const { groups } = useSite(); const [step, setStep] = useState(0); const [age, setAge] = useState(''); const [experience, setExperience] = useState(''); const [interest, setInterest] = useState('all'); const [day, setDay] = useState('all');
  const results: Group[] = filterGroups(groups, { age, day, style: interest });
  const titles = ['Сколько лет ребёнку?', 'Уже пробовали танцевать?', 'Что больше нравится?', 'Когда удобно заниматься?', 'Вот с чего можно начать.'];
  const next = () => setStep(s => s + 1);
  return <div className="quiz"><Eyebrow>НАЙДЁМ СВОЮ ГРУППУ</Eyebrow><div className="quiz-progress" aria-label={`Шаг ${Math.min(step + 1, 4)} из 4`}>{[0, 1, 2, 3].map(s => <span key={s} className={step >= s ? 'active' : ''} />)}</div><DialogTitle>{titles[step]}</DialogTitle><DialogDescription>{step === 4 ? 'Это варианты по возрасту, интересу и времени. Уровень и наличие мест подтвердит администратор.' : 'Несколько простых вопросов. Ничего не нужно знать о танцах заранее.'}</DialogDescription>{step === 0 && <><label className="quiz-age-label">Точный возраст<input type="number" aria-label="Точный возраст ребёнка" min="4" max="17" placeholder="Например, 8" value={age} onChange={e => setAge(e.target.value)} /></label><Button disabled={!age || Number(age) < 4 || Number(age) > 17 || !Number.isInteger(Number(age))} onClick={next}>Дальше <ArrowRight size={18} /></Button></>}{step === 1 && <div className="quiz-options">{['Никогда — начинаем с нуля', 'Немного занимались', 'Танцуем сейчас'].map(s => <button key={s} onClick={() => { setExperience(s); next(); }}>{s}<ArrowRight size={18} /></button>)}</div>}{step === 2 && <div className="quiz-options">{[['all', 'Пока не знаем — хотим попробовать'], ['Hip-Hop', 'Hip-Hop и современная музыка'], ['Girls Hip-Hop', 'Яркая хореография'], ['Afro', 'Энергия и пластика'], ['Jazz-Funk', 'Артистичность и подача'], ['Dance Mix', 'Разные танцевальные стили']].map(([value, label]) => <button key={value} onClick={() => { setInterest(value); next(); }}>{label}<ArrowRight size={18} /></button>)}</div>}{step === 3 && <div className="quiz-options">{[['all', 'Любое время'], ['early', 'Будни до 17:00'], ['late', 'Будни с 17:00'], ['weekend', 'Выходные']].map(([value, label]) => <button key={value} onClick={() => { setDay(value); next(); }}>{label}<ArrowRight size={18} /></button>)}</div>}{step === 4 && <><div className="quiz-result-summary">{age} лет · {experience}</div>{results.length ? <><p>Вариантов по расписанию: {results.length}</p><div className="quiz-results">{results.map(g => <button key={g.id} onClick={() => book(g, age, experience)}><span><b>{g.style}</b><small>{g.days} · {g.time} · {g.age}</small></span><ArrowUpRight size={22} /></button>)}</div></> : <div className="empty-state"><h3>Нужна помощь администратора.</h3><p>Подтверждённых вариантов по этим параметрам нет. Например, возраст группы Hip-Hop пока не указан — мы не включаем её в автоматическую рекомендацию.</p></div>}<Button onClick={() => book(undefined, age, `Опыт: ${experience}; интерес: ${interest}; время: ${day}`)}>Помогите с выбором <ArrowRight size={18} /></Button></>}{step > 0 && <button className="quiz-back" onClick={() => setStep(step - 1)}>← Назад</button>}</div>;
}
function FeedbackForm() {
  const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); setBusy(true); setError(''); try { const response = await fetch('/api/enquiries', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Requested-With': 'YOUKEY' }, body: JSON.stringify({ kind: 'feedback', name: data.get('name'), phone: data.get('phone'), message: data.get('message'), group: 'Обратная связь', consent: data.get('consent') === 'on', website: data.get('website') }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setSent(true); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось сохранить сообщение.'); } finally { setBusy(false); } }
  return <><Eyebrow>МЫ НА СВЯЗИ</Eyebrow><DialogTitle>{sent ? 'Сообщение сохранено.' : 'Давайте разберёмся.'}</DialogTitle><DialogDescription>{sent ? 'Ваш вопрос появился в системе YOUKEY. Администратор сможет связаться с вами по указанному телефону.' : 'Есть вопрос о занятиях? Оставьте сообщение и телефон для ответа.'}</DialogDescription>{!sent && <form className="booking-form" onSubmit={submit}><label className="honeypot" aria-hidden="true">Не заполнять<input name="website" tabIndex={-1} autoComplete="off" /></label><label>Как к вам обращаться<input name="name" autoComplete="name" required minLength={2} maxLength={80} placeholder="Ваше имя" /></label><label style={{marginTop:16}}>Телефон<input name="phone" type="tel" autoComplete="tel" required placeholder="+7 (999) 123-45-67" maxLength={22} /></label><label style={{marginTop:16}}>Ваш вопрос<textarea name="message" rows={4} required minLength={5} maxLength={4000} placeholder="Напишите, что хотели бы узнать" /></label><label className="consent-label"><input type="checkbox" name="consent" required /><span>Согласен на обработку данных по <a href="/privacy" target="_blank" rel="noreferrer">условиям конфиденциальности</a>.</span></label><div className="form-error" role="alert">{error}</div><Button disabled={busy} type="submit">{busy ? 'Сохраняем…' : 'Отправить сообщение'}<ArrowUpRight size={18} /></Button></form>}</>;
}
function VideoModal({ id, title }: { id: string; title: string }) { const [load, setLoad] = useState(false); return <><DialogTitle>{title}</DialogTitle><DialogDescription>Реальное видео со страницы школы. Воспроизведение через YouTube.</DialogDescription>{load ? <iframe className="video-frame" src={`https://www.youtube-nocookie.com/embed/${id}?autoplay=1`} title={title} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen /> : <button className="video-consent" onClick={() => setLoad(true)}><Play size={40} fill="currentColor" /><span>Загрузить видео</span><small>Откроется проигрыватель YouTube</small></button>}<a className="text-link" href={`https://www.youtube.com/watch?v=${id}`} target="_blank" rel="noreferrer">Открыть на YouTube <ArrowUpRight size={16} /></a></>; }
function DetailPage({ path, book }: { path: string; book: Booking }) {
  const { ages, styles } = useSite(); const adult = path === '/adults'; const age = ages.find(a => path === `/ages/${a.slug}`); const style = styles.find(s => path === `/styles/${s.slug}`);
  const title = adult ? 'ТВОЁ ВРЕМЯ.\nТВОЙ РИТМ.' : age ? `${age.title}.\n${age.label} лет.` : style?.name;
  const description = adult ? 'Танцы 18+ в YOUKEY. Выдели время для музыки, движения и себя. Группы для взрослых — со своим расписанием.' : age?.text || style?.text;
  return <><section className={`detail-hero section ${adult ? 'adult-hero' : ''}`}><div><a href="/" className="breadcrumb">Главная / {adult ? 'Танцы 18+' : age ? 'По возрасту' : 'Направления'}</a><Eyebrow>{adult ? 'YOUKEY / 18+' : age ? 'YOUKEY / НАЙДИ СВОИХ' : style?.tag}</Eyebrow><h1>{title?.split('\n').map((t, i) => <span key={i}>{t}<br /></span>)}</h1><p>{description}</p><Button onClick={() => book(undefined, adult ? '18' : undefined, title)}> {adult ? 'Уточнить условия' : 'Попробовать бесплатно'}<ArrowUpRight /></Button>{adult && <p className="fine-print">Стоимость и условия пробного для взрослых уточняются отдельно.</p>}</div><Photo name={adult ? 'dance' : age?.image || style?.image || 'team'} alt="Танцевальная жизнь школы YOUKEY" eager /></section>{age && <div className="section age-detail-info"><h2>Можно начать<br />с первого движения.</h2><p>Опыт и темп у каждого свои. Поможем познакомиться с педагогом, попробовать занятие и выбрать подходящий формат. Состав группы и уровень подтвердим перед визитом.</p></div>}<Schedule key={path} book={book} adult={adult} initialAge={age?.slug || ''} initialStyle={style?.name || 'all'} />{!adult && <Trial book={book} />}<Contacts book={book} adult={adult} /></>;
}
function Privacy() { return <section className="section legal-page"><a className="breadcrumb" href="/">← На главную</a><Eyebrow>ЛОКАЛЬНОЕ ПРЕВЬЮ</Eyebrow><h1>Конфиденциальность</h1><p>Этот сайт работает локально на компьютере владельца проекта и не опубликован.</p><h2>Что сохраняется</h2><p>При отправке формы с вашим согласием сохраняются имя, телефон, возраст, выбранная группа и ответы подбора. Данные записываются в базу сайта, доступны в админке и могут отправляться на почту, которую подключит владелец. До подключения почты уведомления не отправляются. Для проверки рекомендуется использовать тестовые данные.</p><h2>Внешние сервисы</h2><p>Аналитика и рекламные пиксели не подключены. Изображения и шрифты хранятся локально. Проигрыватель YouTube загружается только после нажатия соответствующей кнопки. Ссылки на Telegram, VK и Яндекс Карты открывают сайты этих сервисов.</p><h2>Перед публикацией</h2><p>Владелец должен утвердить действующую политику обработки персональных данных, реквизиты оператора, сроки хранения, порядок отзыва согласия и канал получения заявок. Доступ к админке локально ограничен этим компьютером; перед публичным запуском необходимо установить пароль. Этот текст описывает только локальную демонстрационную версию.</p></section>; }
export default function App() {
  const { ages, styles, videos } = useSite();
  const [modal, setModal] = useState<Modal>(null); const [modalKey, setModalKey] = useState(0); const previousFocus = useRef<HTMLElement | null>(null);
  const path = window.location.pathname.replace(/\/$/, '') || '/';
  function open(next: Modal) { if (!modal) previousFocus.current = document.activeElement as HTMLElement; setModalKey(k => k + 1); setModal(next); }
  const book: Booking = (group, age, context) => open({ type: 'booking', group, age: age || (path === '/adults' ? '18' : undefined), context });
  const video = () => open({ type: 'video', id: videos?.trial || 'OFEzlt4jofM', title: 'Как проходят тренировки в YOUKEY' });
  const isDetail = path === '/adults' || ages.some(a => path === `/ages/${a.slug}`) || styles.some(s => path === `/styles/${s.slug}`);
  useEffect(() => {
    const detail = ages.find(a => path === `/ages/${a.slug}`)?.title || styles.find(s => path === `/styles/${s.slug}`)?.name;
    document.title = path === '/' ? 'YOUKEY — танцы для детей и подростков в Отрадном' : `${detail || (path === '/adults' ? 'Танцы 18+' : path === '/parents' ? 'Родителям' : path === '/privacy' ? 'Конфиденциальность' : path === '/admin' ? 'Админка' : 'Страница не найдена')} — YOUKEY`;
    const meta = document.querySelector('meta[name="description"]');
    if (detail || path === '/adults') meta?.setAttribute('content', `${detail || 'Танцы для взрослых'} в YOUKEY. Расписание занятий. Москва, Алтуфьевское шоссе, 16.`);
  }, [path, ages, styles]);
  useEffect(() => { const feedback = () => { previousFocus.current = document.activeElement as HTMLElement; setModalKey(k => k + 1); setModal({ type: 'feedback' }); }; window.addEventListener('youkey-feedback', feedback); return () => window.removeEventListener('youkey-feedback', feedback); }, []);
  if (path === '/admin') return <Suspense fallback={<div className="admin-loading">Загружаем админку…</div>}><Admin /></Suspense>;
  return <><div id="top" /><a className="skip-link" href="#main">Перейти к содержимому</a><Header book={book} adult={path === '/adults'} /><main id="main">{path === '/' ? <><Hero book={book} quiz={() => open({ type: 'quiz' })} video={video} /><RhythmStrip /><AgeSection /><About quiz={() => open({ type: 'quiz' })} video={video} /><StylesSection /><Trial book={book} /><Schedule book={book} /><Teachers video={video} /><Community video={() => open({ type: 'video', id: videos?.stage || 'lIqcE91KMq4', title: 'Отчётный концерт школы' })} /><Reviews video={() => open({ type: 'video', id: videos?.review || 'mcga00s9r9U', title: 'Родители о школе YOUKEY' })} /><Prices book={book} /><FAQ /><Contacts book={book} /></> : isDetail ? <DetailPage path={path} book={book} /> : path === '/privacy' ? <Privacy /> : path === '/parents' ? <><div className="section parents-intro"><Eyebrow>РОДИТЕЛЯМ</Eyebrow><h1>Первый шаг —<br />без лишних тревог.</h1><p>Что нужно знать до первого занятия и покупки абонемента.</p></div><FAQ /><Trial book={book} /><Contacts book={book} /></> : <div className="section not-found"><Eyebrow>404</Eyebrow><h1>Сбились с ритма?</h1><p>Такой страницы нет. Вернёмся к танцам.</p><Button asChild><a href="/">На главную <ArrowRight /></a></Button></div>}</main><Footer /><div className="mobile-cta"><span>{path === '/adults' ? 'Танцы 18+' : 'Первый шаг —'}<b>{path === '/adults' ? 'в YOUKEY' : 'бесплатно'}</b></span><Button size="small" onClick={() => book()}>Записаться <ArrowUpRight size={18} /></Button></div><Dialog open={modal !== null} onOpenChange={v => { if (!v) setModal(null); }}><DialogContent className={modal?.type === 'video' ? 'video-dialog' : ''} onCloseAutoFocus={e => { e.preventDefault(); previousFocus.current?.focus({ preventScroll: true }); }}><div key={modalKey}>{modal?.type === 'booking' && <BookingForm modal={modal} />}{modal?.type === 'quiz' && <Quiz book={book} />}{modal?.type === 'feedback' && <FeedbackForm />}{modal?.type === 'video' && <VideoModal id={modal.id} title={modal.title} />}</div></DialogContent></Dialog></>;
}
